version: "3.8"
services:
  timf-voc-task-database:
    container_name: timf-voc-task-database
    build:
      context: ./database
    image: mysql:8.0.33
    environment:
      - MYSQL_DATABASE=timf-voc-task
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3300:3306"
